kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: skupper-service-controller
rules:
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
    apiGroups:
      - ''
    resources:
      - services
      - configmaps
      - pods
      - secrets
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
    apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - apps
    resources:
      - daemonsets
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - route.openshift.io
    resources:
      - routes
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
