kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: skupper-router
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - pods
      - configmaps
